"""creating user and blog tables migration

Revision ID: 7267c4c3eebf
Revises: 1cf93f6126ab
Create Date: 2023-09-26 21:43:55.001269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7267c4c3eebf'
down_revision = '1cf93f6126ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
