"""creating user and blog tables migration

Revision ID: cf1a115d03e2
Revises: 7267c4c3eebf
Create Date: 2023-09-26 21:54:21.035276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1a115d03e2'
down_revision = '7267c4c3eebf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
